import { Button, buttonVariants } from '@/components/ui/button';
import { ADD_TEXT, ADD_ITEMS, ADD_CAPTIONS } from '@designcombo/state';
import { dispatch } from '@designcombo/events';
import { useIsDraggingOverTimeline } from '@/features/editor/hooks/use-is-dragging-over-timeline';
import Draggable from '@/components/shared/draggable';
import { TEXT_ADD_PAYLOAD, TEXT_BODY_ADD_PAYLOAD } from '@/features/editor/constants/payload';
import { cn } from '@/lib/utils';
import { nanoid } from 'nanoid';
import { Separator } from '@/components/ui/separator';
import useStore from '@/features/editor/stores/use-store';

export const Texts = () => {
  const isDraggingOverTimeline = useIsDraggingOverTimeline();
  const { size } = useStore();

  const handleAddText = () => {
    dispatch(ADD_TEXT, {
      payload: { ...TEXT_ADD_PAYLOAD, id: nanoid() },
      options: { size },
    });

  };

  const handleAddBodyText = () => {
    dispatch(ADD_TEXT, {
      payload: { ...TEXT_BODY_ADD_PAYLOAD, id: nanoid() },
      options: { size },
    });

  };

  const handleAddCaption = () => {
    const captionPayload = {
      ...TEXT_BODY_ADD_PAYLOAD,
      id: nanoid(),
      type: 'caption',
      details: {
        ...TEXT_BODY_ADD_PAYLOAD.details,
        text: 'Caption Text',
      },
      metadata: {
        type: 'caption',
        autoGenerated: false,
      },
    };

    dispatch(ADD_CAPTIONS, {
      payload: {
        trackItems: [captionPayload],
        tracks: [
          {
            id: nanoid(),
            type: 'caption',
            items: [captionPayload.id],
            accepts: ['caption', 'text'],
            magnetic: false,
            static: false,
          },
        ],
      },
      options: { size },
    });

  };

  return (
    <div className='flex flex-col bg-[#27272A] rounded-[5px] text-white'>
      <h1 className='text-sm p-3'>Text</h1>
      <Separator className='w-full bg-white/60' />

      <div className='flex flex-col gap-2 p-3'>
        <Draggable
          data={TEXT_ADD_PAYLOAD}
          renderCustomPreview={
            <Button
              variant='secondary'
              className='cursor-pointer text-white bg-white/20 hover:bg-white/15 rounded h-10 font-light'
            >
              Add text
            </Button>
          }
          shouldDisplayPreview={!isDraggingOverTimeline}
        >
          <div
            onClick={handleAddText}
            className={cn(
              buttonVariants({ variant: 'default' }),
              'cursor-pointer text-white bg-white/20 hover:bg-white/15 rounded h-10 font-light',
            )}
          >
            Heading
          </div>
        </Draggable>
        <Draggable
          data={TEXT_BODY_ADD_PAYLOAD}
          renderCustomPreview={
            <Button
              variant='secondary'
              className='cursor-pointer text-white bg-white/20 hover:bg-white/15 rounded h-10 font-light'
            >
              Add body text
            </Button>
          }
          shouldDisplayPreview={!isDraggingOverTimeline}
        >
          <div
            onClick={handleAddBodyText}
            className={cn(
              buttonVariants({ variant: 'default' }),
              'cursor-pointer text-white bg-white/20 hover:bg-white/15 rounded h-10 font-light',
            )}
          >
            Body Text
          </div>
        </Draggable>
      </div>
    </div>
  );
};
